# fly.toml app configuration file generated for gta-wasted-generator on 2025-07-09T08:53:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gta-wasted-generator'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "gta_data"
  destination = "/data"